### ISSUE TITLE
Design revisions

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/cpal-site#18]
There are a couple of errors and styling changes that are very small:

**Sitewide**

- [ ] Change logo colour to #666A53 so it matches the colours of the site better
- [ ] There appear to be two X's in the menu next to close
- [ ] Make all #000 text #2C390B
- [ ] Reduce weight of Louize display text under Comerica logo in footer and weight of 'Enter your email address'
- [ ] The height of the header that slides down on scroll feels really nice. It's around 65px. Could we make the default header space that height too?

**Homepage**

- [ ] 'All Dallas neighborhoods should have what they need to thrive.' looks great on largest devices but feels a bit small when device width is between 750px and 1250px. Maybe it can be 36px with 40px line height in this instance?
- [ ] hero red text - make it #D83218 so it passes contrast for accessibility
- [ ] Reduce weight of all text on the left in the animation.
- [ ] Make 'go to the explorer' text in the animation #D83218 so it passes contrast for accessibility. Or we keep the colour and make it larger than 24px.
- [ ] The map in the background of the animation looks a little blurry on retina. I found a way to take very high res screenshots of the mapbox map using Developer Tools and selecting custom size. Maybe this will help?

**Explorer in action index page**
- [ ] Change the hero background colour for the featured post so it w
orks with the site colour
- [ ] Increase line width for 'How the CRE is informing policy and community understanding in Dallas'.  so tthe line break works better.
- [ ] Set 'The Explorer in Action' in Louize display
- [ ] I have created a mockup in the bottom of 'Website Mockups' page.

**FAQ page**

- [ ] Make 'Frequently Asked Questions' in the hero smaller - around 14px/16px
- [ ] Make hover colour #697A21 for questions
- [ ] Change the colour of Methods paper buttons on hover. The red doesn't work so well here. The height for this whole section needs to be taller so that the side-menu doesn't overlap with the footer. We can use a graphic here and put extra padding between this section and the footer. I have created a mockup and put it in the bottom of 'Website Mockups' page.
